"""LLM fix sub-agent with guarded file-edit output."""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import PurePosixPath
import re
from typing import Any

from agent_swarms.config import Settings
from agent_swarms.sandbox.service import SandboxService
from agent_swarms.state.enums import ProviderBackend
from agent_swarms.state.schemas import RepoMapSummary, ReviewFinding, ReviewReport

FIX_SUB_AGENT_SYSTEM_PROMPT = """
You are a careful repository fix sub-agent.
You may generate complete replacement file content, but only for files listed in allowed_files.
Return JSON only. Do not wrap the JSON in markdown.
Schema:
{
  "summary": "short user-facing summary",
  "changes": [
    {
      "path": "relative/path",
      "reason": "why this edit is safe and useful",
      "fixed_finding_titles": ["exact finding title"],
      "content": "full replacement file content"
    }
  ]
}
Rules:
- Only edit files from allowed_files.
- Return full replacement content for each changed file.
- Keep edits small, focused, and related to the user request or review findings.
- For README edits, write useful project-specific documentation, not advice like "document this".
- For code edits, preserve public behavior, do not invent dependencies, and keep fixes small.
- Never write real secrets, tokens, credentials, or private keys.
- If you are not confident, return {"summary": "...", "changes": []}.
""".strip()

EDITABLE_EXTENSIONS = {
    ".css",
    ".html",
    ".js",
    ".json",
    ".jsx",
    ".md",
    ".py",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".yaml",
    ".yml",
}
BLOCKED_FILE_NAMES = {".env", "package-lock.json", "pnpm-lock.yaml", "poetry.lock"}
MAX_FILES_FOR_PROMPT = 6
MAX_FILE_CHARS = 16000
MAX_README_CHARS = 32000
MAX_CHANGE_CHARS = 60000
MAX_CHANGES = 4


@dataclass(frozen=True)
class FixChange:
    """One validated file edit generated by the fix sub-agent."""

    path: str
    content: str
    reason: str
    fixed_finding_titles: list[str]


@dataclass(frozen=True)
class FixAgentResult:
    """Structured result returned by the fix sub-agent."""

    summary: str
    changes: list[FixChange]
    backend: ProviderBackend
    used_llm: bool
    error: str | None = None


class FixSubAgent:
    """Generate guarded README/code edits from review evidence."""

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._client = self._build_client(settings)

    async def generate_fixes(
        self,
        *,
        run_id: str,
        sandbox_service: SandboxService,
        report: ReviewReport,
        user_query: str,
        repo_name: str,
    ) -> FixAgentResult:
        """Ask the LLM for safe file edits, then validate the structured output."""

        if self._client is None:
            return FixAgentResult(
                summary="LLM fix agent is disabled; using deterministic fixers.",
                changes=[],
                backend=ProviderBackend.MOCK,
                used_llm=False,
            )

        allowed_paths = _build_allowed_paths(report, user_query)
        file_payloads = await _read_allowed_files(
            run_id=run_id,
            sandbox_service=sandbox_service,
            allowed_paths=allowed_paths,
        )
        if not allowed_paths:
            return FixAgentResult(
                summary="No safe target files were available for the LLM fix agent.",
                changes=[],
                backend=self._settings.llm_backend,
                used_llm=False,
            )

        prompt = {
            "repo_name": repo_name,
            "user_query": user_query,
            "repo_map": _repo_map_brief(report.repo_map),
            "findings": [_finding_brief(finding) for finding in report.top_findings[:8]],
            "allowed_files": sorted(allowed_paths),
            "files": file_payloads,
        }
        raw_result = await self._generate(json.dumps(prompt, sort_keys=True))
        if raw_result.error is not None:
            return raw_result

        return _validate_result(
            payload_text=raw_result.summary,
            allowed_paths=allowed_paths,
            valid_finding_titles={finding.title for finding in report.top_findings},
            backend=self._settings.llm_backend,
        )

    def _build_client(self, settings: Settings):
        if settings.llm_backend is not ProviderBackend.NVIDIA or not settings.nvidia_api_key:
            return None

        try:
            from langchain_nvidia_ai_endpoints import ChatNVIDIA
        except ImportError:
            return None

        return ChatNVIDIA(
            nvidia_api_key=settings.nvidia_api_key,
            model=settings.nvidia_model,
            temperature=0,
        )

    async def _generate(self, user_prompt: str) -> FixAgentResult:
        try:
            from langchain_core.messages import HumanMessage, SystemMessage

            response = await self._client.ainvoke(
                [
                    SystemMessage(content=FIX_SUB_AGENT_SYSTEM_PROMPT),
                    HumanMessage(content=user_prompt),
                ]
            )
        except Exception as exc:
            return FixAgentResult(
                summary="",
                changes=[],
                backend=self._settings.llm_backend,
                used_llm=False,
                error=str(exc),
            )

        content = response.content
        text = content if isinstance(content, str) else " ".join(str(part) for part in content)
        return FixAgentResult(
            summary=text.strip(),
            changes=[],
            backend=self._settings.llm_backend,
            used_llm=True,
        )


def _build_allowed_paths(report: ReviewReport, user_query: str) -> set[str]:
    paths: set[str] = set()
    if _query_targets_readme(user_query) or _has_readme_finding(report.top_findings):
        paths.add(_detect_readme_path(report.repo_map) or "README.md")

    for finding in report.top_findings:
        for raw_path in [*finding.file_paths, *_extract_evidence_paths(finding.evidence)]:
            normalized = _normalize_edit_path(raw_path)
            if normalized and _is_editable_path(normalized):
                paths.add(normalized)

    return set(sorted(paths)[:MAX_FILES_FOR_PROMPT])


async def _read_allowed_files(
    *,
    run_id: str,
    sandbox_service: SandboxService,
    allowed_paths: set[str],
) -> list[dict[str, str]]:
    files: list[dict[str, str]] = []
    for path in sorted(allowed_paths):
        try:
            content = (await sandbox_service.read_file(run_id, path)).content
        except FileNotFoundError:
            content = ""
        limit = (
            MAX_README_CHARS
            if PurePosixPath(path).name.lower().startswith("readme")
            else MAX_FILE_CHARS
        )
        if len(content) > limit:
            continue
        files.append({"path": path, "content": content})
    return files


def _validate_result(
    *,
    payload_text: str,
    allowed_paths: set[str],
    valid_finding_titles: set[str],
    backend: ProviderBackend,
) -> FixAgentResult:
    try:
        payload = json.loads(_extract_json(payload_text))
    except (TypeError, ValueError, json.JSONDecodeError) as exc:
        return FixAgentResult(
            summary="The LLM fix agent returned invalid JSON, so no LLM edit was applied.",
            changes=[],
            backend=backend,
            used_llm=True,
            error=str(exc),
        )

    changes: list[FixChange] = []
    for item in payload.get("changes", [])[:MAX_CHANGES]:
        if not isinstance(item, dict):
            continue
        change = _validate_change(
            item=item,
            allowed_paths=allowed_paths,
            valid_finding_titles=valid_finding_titles,
        )
        if change is not None:
            changes.append(change)

    return FixAgentResult(
        summary=str(payload.get("summary") or "LLM fix agent generated safe edits.").strip(),
        changes=changes,
        backend=backend,
        used_llm=True,
    )


def _validate_change(
    *,
    item: dict[str, Any],
    allowed_paths: set[str],
    valid_finding_titles: set[str],
) -> FixChange | None:
    path = _normalize_edit_path(str(item.get("path") or ""))
    content = item.get("content")
    if path is None or path not in allowed_paths:
        return None
    if not isinstance(content, str) or not content.strip() or len(content) > MAX_CHANGE_CHARS:
        return None
    if PurePosixPath(path).name.lower().startswith("readme") and _has_readme_placeholder(content):
        return None

    raw_titles = item.get("fixed_finding_titles") or []
    fixed_titles = [
        title
        for title in raw_titles
        if isinstance(title, str) and title in valid_finding_titles
    ]
    return FixChange(
        path=path,
        content=content,
        reason=str(item.get("reason") or "LLM fix agent generated this edit.").strip(),
        fixed_finding_titles=fixed_titles,
    )


def _extract_json(text: str) -> str:
    stripped = text.strip()
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", stripped, flags=re.DOTALL)
    if fenced:
        return fenced.group(1)
    start = stripped.find("{")
    end = stripped.rfind("}")
    if start == -1 or end == -1 or end < start:
        raise ValueError("No JSON object found.")
    return stripped[start : end + 1]


def _repo_map_brief(repo_map: RepoMapSummary) -> dict[str, object]:
    return {
        "mapped_file_count": repo_map.mapped_file_count,
        "languages": repo_map.languages,
        "dependency_files": repo_map.dependency_files[:8],
        "entry_points": repo_map.entry_points[:8],
        "test_locations": repo_map.test_locations[:8],
        "docs_files": repo_map.docs_files[:8],
    }


def _finding_brief(finding: ReviewFinding) -> dict[str, object]:
    return {
        "title": finding.title,
        "severity": finding.severity.value,
        "summary": finding.summary,
        "file_paths": finding.file_paths[:5],
        "evidence": finding.evidence[:5],
        "suggested_fix": finding.suggested_fix,
    }


def _detect_readme_path(repo_map: RepoMapSummary) -> str | None:
    return next(
        (
            path.removeprefix("./")
            for path in repo_map.docs_files + repo_map.top_level_files
            if PurePosixPath(path).name.lower() in {"readme.md", "readme"}
        ),
        None,
    )


def _has_readme_finding(findings: list[ReviewFinding]) -> bool:
    return any("readme" in finding.title.lower() for finding in findings)


def _extract_evidence_paths(evidence: list[str]) -> list[str]:
    paths: list[str] = []
    for line in evidence:
        candidate = line.split(":", maxsplit=1)[0].strip()
        if candidate.startswith("./") or "/" in candidate:
            paths.append(candidate)
    return paths


def _normalize_edit_path(raw_path: str) -> str | None:
    normalized = raw_path.strip().removeprefix("./")
    path = PurePosixPath(normalized)
    if not normalized or path.is_absolute() or ".." in path.parts:
        return None
    return path.as_posix()


def _is_editable_path(path: str) -> bool:
    pure_path = PurePosixPath(path)
    if pure_path.name in BLOCKED_FILE_NAMES:
        return False
    if pure_path.name.lower().startswith("readme"):
        return True
    return pure_path.suffix.lower() in EDITABLE_EXTENSIONS


def _has_readme_placeholder(content: str) -> bool:
    placeholder_phrases = (
        "describe the purpose",
        "document how",
        "list the required",
        "document the commands",
        "list the main folders",
        "add concise notes",
    )
    return any(phrase in content.lower() for phrase in placeholder_phrases)


def _query_targets_readme(user_query: str) -> bool:
    normalized = user_query.lower()
    return "readme" in normalized and any(
        keyword in normalized
        for keyword in {"improve", "update", "rewrite", "fix", "edit", "enhance"}
    )
